### ISSUE TITLE
introduce .gitignore

### ISSUE THREAD

**Issue by edewit** [Maoraz05/2D_Game#6]
you have class files checked into git, there files are generated from the source files and binary so they can't be merged. Remove them and a `.gitignore` so git will ignore changes made to things in the target folder

**Comment by LukasW01** [comment]
got added to the `.gitignore` and will merged with the Pull-Request here

https://github.com/Maoraz05/2D_Game/pull/7

**Comment by Maoraz05** [comment]
got merged. thanks for pointing out 👍
